workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Workouttracker-codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.nathanbyrne.workouttrackerapp
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -maxdepth 2 -execdir pod install \;
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
