workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Workouttracker-codemagic
    environment:
      groups:
        - ios_signing
      vars:
        BUNDLE_ID: com.nathanbyrne.workouttrackerapp
        APP_STORE_APPLE_ID: "6804228254"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -maxdepth 2 -execdir pod install \;
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter unit tests
        script: flutter test
      - name: Set up keychain
        script: keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Add certificates to keychain
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Flutter build ipa
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID")
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          flutter build ipa --release \
            --build-number=$NEW_BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        beta_groups:
          - App Store Connect Users
