create table public.workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  start_time timestamptz,
  end_time timestamptz,
  created_at timestamptz
);

create table public.exercises (
  id bigint generated by default as identity primary key,
  name text,
  sets integer,
  reps integer,
  weight integer,
  start_time timestamptz,
  end_time timestamptz,
  workout_id bigint not null
    references public.workouts (id) on delete cascade,
  exercise_number integer
);

create table public.exercise_sets (
  id bigint generated by default as identity primary key,
  exercise_id bigint not null
    references public.exercises (id) on delete cascade,
  set_number integer,
  reps integer,
  weight double precision
);

create index workouts_user_id_start_time_idx
  on public.workouts (user_id, start_time desc);
create index exercises_workout_id_start_time_idx
  on public.exercises (workout_id, start_time);
create index exercise_sets_exercise_id_id_idx
  on public.exercise_sets (exercise_id, id);

alter table public.workouts enable row level security;
alter table public.exercises enable row level security;
alter table public.exercise_sets enable row level security;

revoke all on table public.workouts from anon;
revoke all on table public.exercises from anon;
revoke all on table public.exercise_sets from anon;

grant select, insert, update, delete
  on table public.workouts, public.exercises, public.exercise_sets
  to authenticated;
grant select, insert, update, delete
  on table public.workouts, public.exercises, public.exercise_sets
  to service_role;

revoke all on sequence public.workouts_id_seq from anon;
revoke all on sequence public.exercises_id_seq from anon;
revoke all on sequence public.exercise_sets_id_seq from anon;

grant usage, select
  on sequence public.workouts_id_seq,
              public.exercises_id_seq,
              public.exercise_sets_id_seq
  to authenticated;
grant usage, select
  on sequence public.workouts_id_seq,
              public.exercises_id_seq,
              public.exercise_sets_id_seq
  to service_role;

create policy "Users can read their workouts"
  on public.workouts
  for select
  to authenticated
  using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can create their workouts"
  on public.workouts
  for insert
  to authenticated
  with check (
    (select auth.uid()) is not null and (select auth.uid()) = user_id
  );

create policy "Users can update their workouts"
  on public.workouts
  for update
  to authenticated
  using ((select auth.uid()) is not null and (select auth.uid()) = user_id)
  with check (
    (select auth.uid()) is not null and (select auth.uid()) = user_id
  );

create policy "Users can delete their workouts"
  on public.workouts
  for delete
  to authenticated
  using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can read exercises in their workouts"
  on public.exercises
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.workouts
      where workouts.id = exercises.workout_id
        and workouts.user_id = (select auth.uid())
    )
  );

create policy "Users can create exercises in their workouts"
  on public.exercises
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.workouts
      where workouts.id = exercises.workout_id
        and workouts.user_id = (select auth.uid())
    )
  );

create policy "Users can update exercises in their workouts"
  on public.exercises
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.workouts
      where workouts.id = exercises.workout_id
        and workouts.user_id = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1
      from public.workouts
      where workouts.id = exercises.workout_id
        and workouts.user_id = (select auth.uid())
    )
  );

create policy "Users can delete exercises in their workouts"
  on public.exercises
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.workouts
      where workouts.id = exercises.workout_id
        and workouts.user_id = (select auth.uid())
    )
  );

create policy "Users can read sets in their workouts"
  on public.exercise_sets
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.exercises
      join public.workouts on workouts.id = exercises.workout_id
      where exercises.id = exercise_sets.exercise_id
        and workouts.user_id = (select auth.uid())
    )
  );

create policy "Users can create sets in their workouts"
  on public.exercise_sets
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.exercises
      join public.workouts on workouts.id = exercises.workout_id
      where exercises.id = exercise_sets.exercise_id
        and workouts.user_id = (select auth.uid())
    )
  );

create policy "Users can update sets in their workouts"
  on public.exercise_sets
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.exercises
      join public.workouts on workouts.id = exercises.workout_id
      where exercises.id = exercise_sets.exercise_id
        and workouts.user_id = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1
      from public.exercises
      join public.workouts on workouts.id = exercises.workout_id
      where exercises.id = exercise_sets.exercise_id
        and workouts.user_id = (select auth.uid())
    )
  );

create policy "Users can delete sets in their workouts"
  on public.exercise_sets
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.exercises
      join public.workouts on workouts.id = exercises.workout_id
      where exercises.id = exercise_sets.exercise_id
        and workouts.user_id = (select auth.uid())
    )
  );
